apiVersion: v1
kind: Pod
metadata:
  name: crash-pod2
spec:
  restartPolicy: Always
  containers:
  - name: crash-container
    image: busybox
    command: ["/bin/sh"]
    args:
      - -c
      - |
        echo "Pod running..."
        sleep 5
        echo "Crashing now"
        exit 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
